### ISSUE TITLE
there is no warning number '4351'

### ISSUE THREAD

**Issue by marakew** [boostorg/system#96]
https://github.com/boostorg/system/blob/9a6d79b84147854aa919644b56b8553f5a2bedb8/include/boost/system/detail/error_category.hpp#L53

MSVC seems unsupport this warning 

iam use MSVC 19/ 14.29.30133 
cl.exe
Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30146 for x64
with -std:c++20

so i got 

boost/system/detail/error_category.hpp(53): warning C4619: #pragma warning: there is no warning number '4351'

**Comment by pdimov** [comment]
I can't reproduce this. I'm trying the following program
```
#include <boost/system.hpp>
#include <iostream>

int main()
{
	std::cout << _MSC_FULL_VER << std::endl;
}
```
under VS 2019, and there's no warning. (The output is `192930146`, so it's the same version of the compiler.)

**Comment by marakew** [comment]
yes i have the same _MSC_FULL_VER output
let me do small research about warning

**Comment by marakew** [comment]
iam enable many warning for cl.exe
so with /w14619
i got - there is no warning number '4351'

**Comment by pdimov** [comment]
Yes, it looks like 4619 is disabled by default. There's another warning, 4616, for warning numbers that are even more invalid. :-)

It seems that warning 4351 has been removed in VS 2015 and later, so I'll disable it only for earlier versions.

**Comment by marakew** [comment]
ok will wait fix in upstream

**Comment by pdimov** [comment]
Should be fixed with https://github.com/boostorg/system/commit/7ae6b317f3325bf722773ba7e5855c37811b3388.

**Comment by marakew** [comment]
i mean at master of boost
https://github.com/boostorg/boost/tree/master/libs
system @ 9a6d79b   8 days ago
still not update

**Comment by pdimov** [comment]
Yes, I will update `master` as well, once CI passes on `develop`.

**Comment by marakew** [comment]
it seems ok, can be close issue
